name: SurvivalPlugin
version: '${project.version}'
main: com.thekhosa.survivalplugin.SurvivalPlugin
api-version: '1.20'
author: TheKhosa
description: Random spawn and wild teleportation plugin

commands:
  wild:
    description: Teleport to a random location
    usage: /<command>
    permission: survival.wild
    permission-message: You don't have permission to use this command

permissions:
  survival.wild:
    description: Allows the use of /wild command
    default: true
